#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : collectl
Version  : 4.3.4
Release  : 27
URL      : https://sourceforge.net/projects/collectl/files/collectl/collectl-4.3.4/collectl-4.3.4.src.tar.gz
Source0  : https://sourceforge.net/projects/collectl/files/collectl/collectl-4.3.4/collectl-4.3.4.src.tar.gz
Source1  : collectl.service
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: collectl-bin = %{version}-%{release}
Requires: collectl-data = %{version}-%{release}
Requires: collectl-license = %{version}-%{release}
Requires: collectl-man = %{version}-%{release}
Requires: collectl-services = %{version}-%{release}
Patch1: collectl-makefile.patch

%description
If you're real lazy, just run INSTALL and it will install collectl into the
same locations as the rpm.  It will install as /usr/bin/collectl and all the
other runtime components will be placed into /usr/share/collectl.  If you
really care where everything goes, read the script as it's pretty short.
There's also an UNINSTALL that will completely remove everything.

%package bin
Summary: bin components for the collectl package.
Group: Binaries
Requires: collectl-data = %{version}-%{release}
Requires: collectl-license = %{version}-%{release}
Requires: collectl-services = %{version}-%{release}

%description bin
bin components for the collectl package.


%package data
Summary: data components for the collectl package.
Group: Data

%description data
data components for the collectl package.


%package doc
Summary: doc components for the collectl package.
Group: Documentation
Requires: collectl-man = %{version}-%{release}

%description doc
doc components for the collectl package.


%package license
Summary: license components for the collectl package.
Group: Default

%description license
license components for the collectl package.


%package man
Summary: man components for the collectl package.
Group: Default

%description man
man components for the collectl package.


%package services
Summary: services components for the collectl package.
Group: Systemd services

%description services
services components for the collectl package.


%prep
%setup -q -n collectl
cd %{_builddir}/collectl
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1661352215
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1661352215
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/collectl
cp %{_builddir}/collectl/COPYING %{buildroot}/usr/share/package-licenses/collectl/06b0317b87e80c20ce780dea1d5f207fd95e90f4
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/collectl.service

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/collectl
/usr/bin/colmux

%files data
%defattr(-,root,root,-)
/usr/share/collectl/UNINSTALL
/usr/share/collectl/envrules.std
/usr/share/collectl/formatit.ph
/usr/share/collectl/gexpr.ph
/usr/share/collectl/graphite.ph
/usr/share/collectl/hello.ph
/usr/share/collectl/lexpr.ph
/usr/share/collectl/misc.ph
/usr/share/collectl/statsd.ph
/usr/share/collectl/util/client.pl
/usr/share/collectl/vmstat.ph
/usr/share/collectl/vmsum.ph
/usr/share/collectl/vnet.ph

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/collectl/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/collectl/06b0317b87e80c20ce780dea1d5f207fd95e90f4

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/collectl.1.gz
/usr/share/man/man1/colmux.1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/collectl.service
