#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : collectl
Version  : 4.0.5
Release  : 12
URL      : http://downloads.sourceforge.net/collectl/collectl-4.0.5.src.tar.gz
Source0  : http://downloads.sourceforge.net/collectl/collectl-4.0.5.src.tar.gz
Source1  : collectl.service
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: collectl-bin
Requires: collectl-config
Requires: collectl-data
Requires: collectl-doc
Patch1: collectl-makefile.patch

%description
If you're real lazy, just run INSTALL and it will install collectl into the
same locations as the rpm.  It will install as /usr/bin/collectl and all the
other runtime components will be placed into /usr/share/collectl.  If you
really care where everything goes, read the script as it's pretty short.
There's also an UNINSTALL that will completely remove everything.

%package bin
Summary: bin components for the collectl package.
Group: Binaries
Requires: collectl-data
Requires: collectl-config

%description bin
bin components for the collectl package.


%package config
Summary: config components for the collectl package.
Group: Default

%description config
config components for the collectl package.


%package data
Summary: data components for the collectl package.
Group: Data

%description data
data components for the collectl package.


%package doc
Summary: doc components for the collectl package.
Group: Documentation

%description doc
doc components for the collectl package.


%prep
%setup -q -n collectl-4.0.5
%patch1 -p1

%build
export LANG=C
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/collectl.service

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/collectl
/usr/bin/colmux

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/collectl.service

%files data
%defattr(-,root,root,-)
/usr/share/collectl/UNINSTALL
/usr/share/collectl/envrules.std
/usr/share/collectl/formatit.ph
/usr/share/collectl/gexpr.ph
/usr/share/collectl/graphite.ph
/usr/share/collectl/hello.ph
/usr/share/collectl/lexpr.ph
/usr/share/collectl/misc.ph
/usr/share/collectl/statsd.ph
/usr/share/collectl/util/client.pl
/usr/share/collectl/util/col2tlviz.pl
/usr/share/collectl/vmstat.ph
/usr/share/collectl/vmsum.ph
/usr/share/collectl/vnet.ph

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/collectl/*
%doc /usr/share/man/man1/*
